version: "3"
services:
  web:
    build: .
    ports:
      - 80:80
    expose:
      - 80
    links:
      - my-mongo
      - my-rabbit
    container_name: tour-editor
    environment:
      SPRING_APPLICATION_JSON: '{\
      "spring": {\
        "profiles": {"active": "default, prod"}\
        "data":{"mongodb":{"uri":"mongodb://one-mongo:27017/panorama-test"}}}, \
      "application": {"baseUrl": "http://52.224.165.47"}}'
    image: downhillski/pannellum-tour-maker:latest
  my-mongo:
    image: mongo
    ports:
      - 27017:27017
    hostname: one-mongo
    container_name: one-mongo
  my-rabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    hostname: one-rabbit
    container_name: one-rabbit