spring:
  profiles:
    active: default, dev

application:
  baseUrl: http://localhost:8080/
  upload:
    directory: /Users/hua/IdeaProjects/pannellum-tour-maker-service/upload-dir
    tours: /Users/hua/IdeaProjects/pannellum-tour-maker-service/upload-dir/tours

---
spring:
  profiles: dev
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

---
spring:
  profiles: prod
  data:
      mongodb:
        host: localhost
        port: 27017
        database: test
  http:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

