spring:
  profiles:
    active: default, dev

application:
  baseUrl: http://localhost:8080/
  nona: /Applications/Hugin/HuginStitchProject.app/Contents/MacOS/nona
  upload:
    directory: /Users/hua/IdeaProjects/pannellum-tour-maker-service/upload-dir
    tours: /Users/hua/IdeaProjects/pannellum-tour-maker-service/upload-dir/tours
    equirectangular: /Users/hua/IdeaProjects/pannellum-tour-maker-service/upload-dir/equirectangular

---
spring:
  profiles: dev
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

---
spring:
  profiles: prod
  data:
      mongodb:
        host: localhost
        port: 27017
        database: test
  http:
      multipart:
        max-file-size: 1000MB
        max-request-size: 1000MB

